#!/usr/bin/env python3
"""Generate `crates/spec-spine-core/src/kit_embedded.rs` from `kit/` (spec 065).

`scaffold_init` is a pure function of `Config` performing no IO, so the kit's
contents must be compiled into the binary for `init --with-kit` to write them.
`include_str!` cannot reach `kit/`: it lives outside the crate, and `cargo
package` ships only what is under the package root, so a published crate built
that way would not contain the kit at all.

So the bytes are copied into a generated module, and a test asserts the module
and the checked-in tree agree. `kit/` stays the editable source; this file is
never edited by hand. Regenerate with:

    python3 scripts/gen-kit-embedded.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates/spec-spine-core/src/kit_embedded.rs"

# Files an adopter receives, at the paths they must live at to work. `kit/` is
# this repository's storage location; `.claude/skills/build/SKILL.md` is where
# the file has to be.
SKIP = {
    # The kit's own documentation, about the kit rather than part of it.
    "kit/README.md",
    # A stanza to append to an existing .gitattributes, not a file to write.
    "kit/.gitattributes-stanza",
    # Spec 065 3.1 requires the scaffold to emit a CONFIG-AWARE `AGENTS.md`
    # unconditionally, and 3.2's list of kit files does not include one. The
    # kit's copy is this repository's template for that protocol; the adopter
    # gets the generated one, whose corpus and derived paths match their layout.
    "kit/AGENTS.md",
}
# Never part of the kit, whatever the filesystem accumulates.
IGNORE = {".DS_Store", "__pycache__", ".git"}

# Destination path for a kit file, when it differs from stripping `kit/`.
REMAP = {
    "kit/govern.yml": ".github/workflows/govern.yml",
    # `kit/` is flat storage; Claude Code reads settings from `.claude/`.
    "kit/settings.json": ".claude/settings.json",
}


def dest_for(rel: str) -> str:
    if rel in REMAP:
        return REMAP[rel]
    return rel[len("kit/") :]


def main() -> int:
    # Walk the tree rather than asking git: a brand-new kit file is untracked
    # until it is staged, and a generator that silently omitted it would ship a
    # binary missing the file its own spec had just added. Junk is excluded by
    # name instead.
    files = [
        p.relative_to(ROOT).as_posix()
        for p in (ROOT / "kit").rglob("*")
        if p.is_file() and not any(part in IGNORE for part in p.parts)
    ]
    entries = []
    for rel in sorted(files):
        if rel in SKIP:
            continue
        text = (ROOT / rel).read_text(encoding="utf-8")
        entries.append((dest_for(rel), text))

    parts = [
        "// @generated by scripts/gen-kit-embedded.py from kit/. Do not edit.\n",
        "//\n",
        "//! The kit, compiled in (spec 065 §3.2).\n",
        "//!\n",
        "//! `scaffold_init` is a pure function of `Config` performing no IO, so\n",
        "//! `init --with-kit` can only write files the binary already carries.\n",
        "//! `include_str!` cannot reach `kit/`: it is outside this crate, and\n",
        "//! `cargo package` ships only what is under the package root, so a\n",
        "//! published crate built that way would carry no kit at all.\n",
        "//!\n",
        "//! `kit/` stays the editable source. `tests/scaffold.rs` asserts this\n",
        "//! module and that tree agree, so an edit to one cannot silently\n",
        "//! diverge from the other, which is the same shape as the conformance\n",
        "//! test pinning DTOs against the embedded JSON Schemas.\n",
        "\n",
        "/// `(destination path, contents)` for every file `--with-kit` writes.\n",
        "/// Destinations are the adopter's own paths, not `kit/`-prefixed ones.\n",
        "///\n",
        "/// `rustfmt::skip`: the entries are raw string literals holding whole\n",
        "/// files, and reflowing the tuples around them churns a generated\n",
        "/// artifact for no reader's benefit.\n",
        "#[rustfmt::skip]\n",
        "pub const KIT_FILES: &[(&str, &str)] = &[\n",
    ]
    for dest, text in entries:
        parts.append(f'    ({rust_str(dest)}, {rust_str(text)}),\n')
    parts.append("];\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(entries)} file(s)")
    return 0


def rust_str(s: str) -> str:
    """A Rust raw string literal with enough hashes to be unambiguous."""
    hashes = "#"
    while f'"{hashes}' in s:
        hashes += "#"
    return f'r{hashes}"{s}"{hashes}'


if __name__ == "__main__":
    sys.exit(main())
